layout: stacked
style: dark
encoding: UTF-8


plugins:
  - jekyll-github-metadata
  - jemoji
  - kramdown
  - jekyll-octicons

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    - flask_demo
    - chuanfuyap
    - WB_Data_Project
    - soslibJNIC
    - Stock_Data_Modelling-DataScienceProject-
    

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: chuanfuyap
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: chuanfuyap
  # unsplash: your_username
  # vk: your_username
  # website: /about
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  #- name: Deep Learning
  #  web_url: https://github.com/topics/deep-learning
  #  image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Multi-Layer_Neural_Network-Vector-Blank.svg/1920px-Multi-Layer_Neural_Network-Vector-Blank.svg.png

  - name: Bayesian Modelling
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bayes_icon.svg/1920px-Bayes_icon.svg.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Ensemble_Boosting.svg/1920px-Ensemble_Boosting.svg.png
  
  #- name: Time Series Analysis
  #  image_url: https://upload.wikimedia.org/wikipedia/commons/7/77/Random-data-plus-trend-r2.png

theme: jekyll-theme-midnight